version: 1.0.{build}.0
image: Visual Studio 2019
platform:
- x86
- x64
configuration:
- Release
install:
- cmd: git submodule -q update --init
- cmd: git clone -q https://github.com/microsoft/DMF.git C:\projects\DMF
build_script:
- cmd: .\build.cmd
artifacts:
- path: 'bin**\$(APPVEYOR_PROJECT_NAME)\*.inf'
- path: 'bin**\$(APPVEYOR_PROJECT_NAME)\*.sys'
- path: 'bin**\*.pdb'
- path: 'bin\*.exe'
deploy:
- provider: Environment
  name: BUILDBOT
  on:
    appveyor_repo_tag: true